# Site Identity
title: Explorational Adventures
email: contact@ecotechexplorers.ninja
description: >-
  Hands-on STEM and sustainability learning powered by EcoTech Explorers. Explore electronics, AI, and green tech with fun projects and accessible guides.

# GitHub Pages deployment
baseurl: "/ExplorationalAdventures"  # Repository name, required for project pages
url: "https://belamar1.github.io"    # GitHub Pages base URL

# Author & Social
twitter_username: ecotech_ninja
github_username: belamar1

# SEO
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM

# Build exclusions (keep default for GitHub Pages)
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/
  - README.md
  - Gemfile
  - Gemfile.lock

# Optional: Enable Google Analytics (uncomment and add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X
